CC=gcc
TOPDIR=../
OBJS=licmd.o likcs.o licmcmd.o
INCS=cc_str.h likcs.h licmd.h
EXECUTABLE=licmd.exe
SELFCALL=make -f Makefile.dos

.PHONY: all clean-obj install

All: $(OBJS)
	$(CC) -o $(EXECUTABLE) $(OBJS)
	$(SELFCALL) clean-obj
	$(SELFCALL) install

%.o: %.c $(INCS)
	$(CC) -c -o $@ $<

clean-obj:
	rm -f $(OBJS)

install:
	mv $(EXECUTABLE) $(TOPDIR)
